NAME = test
TARGETS = test

CARGO_DEPS = macros base64 clap thiserror csv serde chrono regex crossbeam cpu-time heappy
VERUS_DEPS = parser polyfill vest chain rspec_lib
TEST_TARGETS =
VERUS_FLAGS = --no-lifetime

include ../dep.mk
