NAME = test
TARGETS = test

CARGO_DEPS = macros base64 clap thiserror csv serde chrono regex crossbeam cpu-time
VERUS_DEPS = parser polyfill vest vpl chain
TEST_TARGETS =
VERUS_FLAGS = --no-lifetime

include ../dep.mk
