# Based on
# https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-docker-images#publishing-images-to-github-packages

name: Build Docker Image

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Disk Cleanup
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          docker system prune -a -f
          docker builder prune -a -f
          df -h

      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Check Disk Usage
        run: |
          docker image ls
          df -h

      # Build Chromium
      - name: Build Chromium
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          target: chromium-install
          tags: chromium-install
          cache-from: type=gha
          cache-to: type=gha,mode=min

      - name: Check Disk Usage
        run: |
          docker buildx prune --all --force
          docker image ls
          df -h

      # Build Firefox
      - name: Build Firefox
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          target: firefox-install
          tags: firefox-install
          cache-from: type=gha
          cache-to: type=gha,mode=min
      
      - name: Check Disk Usage
        run: |
          docker buildx prune --all --force
          docker image ls
          df -h

      # Build OpenSSL
      - name: Build OpenSSL
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          target: openssl-install
          tags: openssl-install
          cache-from: type=gha
          cache-to: type=gha,mode=min

      - name: Check Disk Usage
        run: |
          docker buildx prune --all --force
          docker image ls
          df -h

      # Build ARMOR
      - name: Build ARMOR
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          target: armor-install
          tags: armor-install
          cache-from: type=gha
          cache-to: type=gha,mode=min

      - name: Check Disk Usage
        run: |
          docker buildx prune --all --force
          docker image ls
          df -h

      # Replace some "AS **-install" in the Dockerfile
      # with an unused name "AS **-install-unused"
      # to force Docker to use previously built layers
      - name: Force use of cached builds
        run: |
          sed -i 's/AS chromium-install/AS chromium-install-unused/g' Dockerfile
          sed -i 's/AS firefox-install/AS firefox-install-unused/g' Dockerfile
          sed -i 's/AS openssl-install/AS openssl-install-unused/g' Dockerfile
          sed -i 's/AS armor-install/AS armor-install-unused/g' Dockerfile

      - name: Build final Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          target: final
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
